### ISSUE TITLE
Publish multi-arch Docker image

### ISSUE THREAD

**Issue by mandrean** [patrickdappollonio/wait-for#21]
Hi,

`goreleaser` seems to build the binary for multiple architectures:
https://github.com/patrickdappollonio/wait-for/blob/master/.goreleaser.yml#L8-L11

But the Docker image is only published for `amd64` which causes some issues on `arm64`, especially when running in `minikube` on Mac:

```sh
❯ docker pull ghcr.io/patrickdappollonio/wait-for:latest --platform linux/arm64

latest: Pulling from patrickdappollonio/wait-for
Digest: sha256:d33d32af072c8d91f476f2c0f6618894de3c59ece5489da561927cbe446ed988
Status: Image is up to date for ghcr.io/patrickdappollonio/wait-for:latest

image with reference ghcr.io/patrickdappollonio/wait-for:latest was found but does not match the specified platform:
wanted linux/arm64, actual: linux/amd64
```

Consider using `docker buildx` and build+publish both `amd64`+`arm64`! Thanks.

https://www.docker.com/blog/how-to-rapidly-build-multi-architecture-images-with-buildx/

**Comment by patrickdappollonio** [comment]
I'll need this myself and the steps seem quite straightforward: https://goreleaser.com/customization/docker_manifest/

I'll try it out as soon as possible, thanks for the report!

**Comment by patrickdappollonio** [comment]
Done! Sorry for the delay... `wait-for` now exposes 2 sets of images: `arm64` and `amd64`:

![image](https://github.com/patrickdappollonio/wait-for/assets/930925/dc624eeb-3cb0-4194-8e33-92fd5a934691)

**Comment by patrickdappollonio** [comment]
Closing for lack of feedback. I'm assuming it works correctly! 😄

**Comment by mandrean** [comment]
Missed your question @patrickdappollonio, too much noise in the GH notifications...

But it works now, yes. Thanks!

```
❯ docker pull ghcr.io/patrickdappollonio/wait-for:latest --platform linux/arm64
latest: Pulling from patrickdappollonio/wait-for
Digest: sha256:432e140af31d86c2d214c771ed0be92398541aafdf75ea4c30fc3908edcfa65e
Status: Image is up to date for ghcr.io/patrickdappollonio/wait-for:latest

❯ docker inspect ghcr.io/patrickdappollonio/wait-for:latest | grep Architecture
        "Architecture": "arm64",
```
